[build]
  publish = "static"
  functions = "functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  NETLIFY = "true"

[[redirects]]
  from = "/api/workflows*"
  to = "/.netlify/functions/workflows-static:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["api-static/**", "database/**", "workflows/**", "src/**"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:; frame-ancestors 'none';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-Requested-With"
    Access-Control-Max-Age = "86400"
    Cache-Control = "public, max-age=300, s-maxage=600"

[[headers]]
  for = "/database/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"